/g4horus/output/type ntuple, hist
/g4horus/output/hist_bin_num 30000
/g4horus/output/hist_min 0. MeV
/g4horus/output/hist_max 3. MeV
/g4horus/gun/read_decay_scheme ../test/test.json
/g4horus/detector/distance 1.3 cm
/g4horus/gun/type cascade
/g4horus/physics_list Shielding
/g4horus/gun/time_min 10
/g4horus/gun/time_max 40

/g4horus/init

/g4horus/gun/energy 919.337
/g4horus/gun/cascade true
/run/printProgress 1000
/analysis/setFileName test_on
/run/beamOn 10000


/g4horus/gun/energy 919.337
/g4horus/gun/cascade false
/run/printProgress 1000
/analysis/setFileName test_off
/run/beamOn 10000
