

install.packages("Rcpp", repos='https://ftp.fau.de/cran/')
install.packages("plyr", repos='https://ftp.fau.de/cran/')
install.packages("tidyr", repos='https://ftp.fau.de/cran/')
install.packages("dplyr", repos='https://ftp.fau.de/cran/')
install.packages("magrittr", repos='https://ftp.fau.de/cran/')
install.packages("data.table", repos='https://ftp.fau.de/cran/')
install.packages("stringr", repos='https://ftp.fau.de/cran/')
install.packages("ggplot2", repos='https://ftp.fau.de/cran/')
install.packages("tidyr", repos='https://ftp.fau.de/cran/')

cat("==================================================================\n\n\n")
cat("testing:\n\n")
cat("loading library stringr...\n")
try({suppressMessages(library(stringr))
cat("loading library stringr successfully\n")})
cat("loading library ggplot2...\n")
try({suppressMessages(library(ggplot2))
cat("loading library ggplot2 successfully\n")})
cat("loading library plyr...\n")
try({suppressMessages(library(plyr))
cat("loading library plyr successfully\n")})
cat("loading library dplyr...\n")
try({suppressMessages(library(dplyr))
cat("loading library dplyr successfully\n")})
cat("loading library tidyr...\n")
try({suppressMessages(library(tidyr))
cat("loading library tidyr successfully\n")})
cat("loading library magrittr...\n")
try({suppressMessages(library(magrittr))
cat("loading library magrittr successfully\n")})
cat("loading library data.table...\n")
try({suppressMessages(library(data.table))
cat("loading library data.table successfully\n")})