/g4horus/output_type hist
/g4horus/gun/read_decay_scheme ../test/test.json
/g4horus/detector/distance 1.3 cm
/g4horus/gun/type cascade
/g4horus/init

/g4horus/gun/energy 919.337
/g4horus/gun/cascade true
/run/printProgress 100
/analysis/setFileName test1_on
/run/beamOn 1000

/g4horus/gun/energy 919.337
/g4horus/gun/cascade false
/run/printProgress 100
/analysis/setFileName test1_off
/run/beamOn 1000
