/run/printProgress 100000
/analysis/setFileName 186_on
/cascade/mode 1
/cascade/energy 186.21 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 186_off
/cascade/mode 0
/cascade/energy 186.21 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 242_on
/cascade/mode 1
/cascade/energy 242.00 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 242_off
/cascade/mode 0
/cascade/energy 242.00 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 295_on
/cascade/mode 1
/cascade/energy 295.22 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 295_off
/cascade/mode 0
/cascade/energy 295.22 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 352_on
/cascade/mode 1
/cascade/energy 351.93 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 352_off
/cascade/mode 0
/cascade/energy 351.93 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 609_on
/cascade/mode 1
/cascade/energy 609.32 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 609_off
/cascade/mode 0
/cascade/energy 609.32 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 665_on
/cascade/mode 1
/cascade/energy 665.45 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 665_off
/cascade/mode 0
/cascade/energy 665.45 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 768_on
/cascade/mode 1
/cascade/energy 768.36 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 768_off
/cascade/mode 0
/cascade/energy 768.36 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 806_on
/cascade/mode 1
/cascade/energy 806.18 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 806_off
/cascade/mode 0
/cascade/energy 806.18 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 934_on
/cascade/mode 1
/cascade/energy 934.06 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 934_off
/cascade/mode 0
/cascade/energy 934.06 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1120_on
/cascade/mode 1
/cascade/energy 1120.29 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1120_off
/cascade/mode 0
/cascade/energy 1120.29 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1155_on
/cascade/mode 1
/cascade/energy 1155.21 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1155_off
/cascade/mode 0
/cascade/energy 1155.21 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1238_on
/cascade/mode 1
/cascade/energy 1238.12 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1238_off
/cascade/mode 0
/cascade/energy 1238.12 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1281_on
/cascade/mode 1
/cascade/energy 1280.98 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1281_off
/cascade/mode 0
/cascade/energy 1280.98 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1378_on
/cascade/mode 1
/cascade/energy 1377.67 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1378_off
/cascade/mode 0
/cascade/energy 1377.67 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1402_on
/cascade/mode 1
/cascade/energy 1401.52 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1402_off
/cascade/mode 0
/cascade/energy 1401.52 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1408_on
/cascade/mode 1
/cascade/energy 1407.99 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1408_off
/cascade/mode 0
/cascade/energy 1407.99 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1509_on
/cascade/mode 1
/cascade/energy 1509.21 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1509_off
/cascade/mode 0
/cascade/energy 1509.21 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1661_on
/cascade/mode 1
/cascade/energy 1661.27 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1661_off
/cascade/mode 0
/cascade/energy 1661.27 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1730_on
/cascade/mode 1
/cascade/energy 1729.60 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1730_off
/cascade/mode 0
/cascade/energy 1729.60 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1764_on
/cascade/mode 1
/cascade/energy 1764.49 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1764_off
/cascade/mode 0
/cascade/energy 1764.49 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1847_on
/cascade/mode 1
/cascade/energy 1847.43 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 1847_off
/cascade/mode 0
/cascade/energy 1847.43 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 2119_on
/cascade/mode 1
/cascade/energy 2118.51 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 2119_off
/cascade/mode 0
/cascade/energy 2118.51 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 2204_on
/cascade/mode 1
/cascade/energy 2204.06 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 2204_off
/cascade/mode 0
/cascade/energy 2204.06 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 2448_on
/cascade/mode 1
/cascade/energy 2447.70 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
/analysis/setFileName 2448_off
/cascade/mode 0
/cascade/energy 2447.70 keV
/cascade/file Decay_Scheme_226Ra
/run/beamOn 1000000
